# Add Homebrew to PATH
export PATH="/Users/samanthacohen/go/bin:$PATH"  
export PATH="/opt/homebrew/bin:$PATH" 
export MSSQL_SA_PASSWORD="yourStrong(!)Password"

# Optionally, initialize Homebrew
if command -v brew &>/dev/null; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi

eval "$(mise activate zsh --shims)"
alias tf=terraform
